### ISSUE TITLE
Hi works great for recap but for arkose labs funcaptcha getting some issues

### ISSUE THREAD

**Issue by smartahsan** [alperensert/capmonster_python#2]
Hey so when create the captcha task it creates a ID for it but then never ends up sending a response with a token or anything. What could be the issue?

**Comment by alperensert** [comment]
If you can share your code for creating/solving funcaptcha, I can help you with that.

**Comment by smartahsan** [comment]
> If you can share your code for creating/solving funcaptcha, I can help you with that.

Hi i have emailed you an example of the code. Please let me know if you have received it.

**Comment by alperensert** [comment]
It gives _[ERROR_CAPTCHA_UNSOLVABLE]_ error. That's not an issue about package.

Can be: 
* You misspelling the website public key
* Capmonster doesn't have ability to solve arkose labs funcaptcha

**Comment by smartahsan** [comment]
> It gives _[ERROR_CAPTCHA_UNSOLVABLE]_ error. That's not an issue about package.
> 
> Can be:
> 
> * You misspelling the website public key
> * Capmonster doesn't have ability to solve arkose labs funcaptcha

Well i copy pasted the website key so i would suppose it would work,
and for the ability to solve on there website they do advertise it. could you attempt to solve it?

**Comment by alperensert** [comment]
Send me the funcaptcha site and token via e mail, I will try

**Comment by smartahsan** [comment]
> Send me the funcaptcha site and token via e mail, I will try

Hi i have sent you the email. Please keep me updated

**Comment by smartahsan** [comment]
Hey any updates?
