### ISSUE TITLE
[HELP] How add customdata to HCaptcha request?

### ISSUE THREAD

**Issue by ChronoBrake** [alperensert/capmonster_python#20]
Hey,

 I have little problem. How to add "rqdata" param to request?
 
 It's my code:
 
```python
 def solveCaptchaWithLib(captchaSitekey, pageUrl):
    capmonster = HCaptchaTask(KEY)
    capmonster.set_user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36")
    task_id = capmonster.create_task(pageUrl, captchaSitekey)
    result = capmonster.join_task_result(task_id)
    return result.get("gRecaptchaResponse")
```

Best Regards

**Comment by alperensert** [comment]
Hey, @ChronoBrake

```python
 def solveCaptchaWithLib(captchaSitekey, pageUrl):
    capmonster = HCaptchaTask(KEY)
    capmonster.set_user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36")
    task_id = capmonster.create_task(website_url: pageUrl, website_key: captchaSitekey, custom_data: "your data")
    result = capmonster.join_task_result(task_id)
    return result.get("gRecaptchaResponse")
```

You can pass the rqdata while using create_task method. It's allowing custom_data as parameter. 
But you should pay attention, custom_data must be string.

For detailed information about HCaptchaTask, check out [here](https://github.com/alperensert/capmonster_python/wiki/2.-API#class-capmonster_pythonhcaptchahcaptchatask).

Best regards,
Alp

**Comment by ChronoBrake** [comment]
Hey, after provide that changes i got error:

```
task_id = capmonster.create_task(website_url: pageUrl, website_key: captchaSitekey, custom_data: customData)
                                            ^
SyntaxError: invalid syntax
```

How i can call that class function in correct way?

Best Regards

**Comment by ChronoBrake** [comment]
EDIT:

Okay, i resolved it.
: must be =
`task_id = capmonster.create_task(website_url=pageUrl, website_key=captchaSitekey, custom_data=customData)`
