### ISSUE TITLE
NoCaptchaTaskProxyless error

### ISSUE THREAD

**Issue by minhtd-fabbi** [alperensert/capmonster_python#4]
![Screen Shot 2021-09-06 at 17 51 10](https://user-images.githubusercontent.com/77663227/132206394-fe7d8259-6649-4808-90b6-4e7a3f04d057.png)
I suddenly got an error when running the `NoCaptchaTaskProxyless` function which was fine 5 hours ago.

**Comment by alperensert** [comment]
Can you run it again? Sometimes capmonster is unable to send any response because of heavy workload. I thought they fixed this problem, if this happens again please write it here.

**Comment by minhtd-fabbi** [comment]
> Can you run it again? Sometimes capmonster is unable to send any response because of heavy workload. I thought they fixed this problem, if this happens again please write it here.

I have run again several times. It's still happening. Do you have any solutions for that?

**Comment by alperensert** [comment]
I didn't see a problem when I tried to solve NoCaptchaTaskProxyless.
Firstly check your balance and after can you share the relevant code?

**Comment by minhtd-fabbi** [comment]
@alperensert sometimes it has an exception with a message like this `Sometimes can be happen if capmonster servers there is too much intensity`. Do you know how to contact them or just the thread?

**Comment by alperensert** [comment]
![resim](https://user-images.githubusercontent.com/63921520/132214313-083ab8f7-c8ac-4c1f-98a4-6c31c31a812c.png)
Your request isn't have _**200 OK**_ status code. It means you cannot perform the post request correctly or api site is down. Like I said I thought they fixed this problem.

**Comment by minhtd-fabbi** [comment]
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from capmonster_python import NoCaptchaTaskProxyless

options = Options()
browser = webdriver.Chrome(options=options, executable_path=ChromeDriverManager().install())
browser.get("https://www.google.com/recaptcha/api2/demo")

website_key = "6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-"
website_url = browser.current_url

captcha = NoCaptchaTaskProxyless(client_key="YOUR_API_KEY")
taskId = captcha.createTask(website_url, website_key)
print("# Task created successfully, waiting for the response.")
response = captcha.joinTaskResult(taskId)
print("# Response received.")
browser.execute_script(f"document.getElementsByClassName('g-recaptcha-response')[0].innerHTML = '{response}';")
print("# Response injected to secret input.")
browser.find_element_by_id("recaptcha-demo-submit").click()
print("# Form submitted.")
```

I just run the sample code, my balance is still enough. And yes it happens when I started to send the request to capmonster in 5 machines

**Comment by alperensert** [comment]
I was worked more than 5 but it's never happen to me for a long time. 
Please follow these steps (may can solve the problem not sure %100):

1. Change your IP
2. Recreate API key from control panel
3. Filter your machines IP's from control panel -> settings -> Filter IP (_not really necessarry, just skip this step_)

After all of these if your problem still not resolved, please contact with support via this [link](https://helpdesk.zennolab.com/en-us/conversation/new)

**Comment by minhtd-fabbi** [comment]
I got it. Thank you for your support.
