### ISSUE TITLE
[HELP] Support to fallback new functionality

### ISSUE THREAD

**Issue by lasoama** [alperensert/capmonster_python#49]
**Your purpose**
I'm trying to use `capmonster_python` with `userAgent` and the [new functionality](https://zennolab.com/discussion/threads/capmonster-cloud-new-functionality.115789/) `fallbackToActualUA`.

`userAgent` is ok, but fallback no.

Will this new functionality be supported soon?

**Comment by alperensert** [comment]
Hi @lasoama,

Thank you for bringing the fallbackToActualUA implementation for capmonster_python with userAgent to my attention. I have successfully incorporated your solution into the library. Your contribution is invaluable to the project's growth.

[Add fallback option to UserAgent tasks](https://github.com/alperensert/capmonster_python/commit/dc68750ef22fc0cf22707c3678b1c5549cc68be5)
