### ISSUE TITLE
DataDome missing from files.

### ISSUE THREAD

**Issue by gangstadresta** [alperensert/capmonster_python#56]
**Describe the bug**
DataDome is missing from the capmonster_python files, yet it is imported in init, this makes the module fail on import.

**To Reproduce**
1. Import the module

**Expected behavior**
The module should import and the program will continue

**Screenshots**
Too lazy, take my word for it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Windows 11 / Ubuntu 

sorry i dont feel like typing anything else this is a blatant bug and can be fixed very easily i dont rlly have to type all this out

**Comment by alperensert** [comment]
Hi @gangstadresta, 

I really doesn't know how I made a major mistake like this. I will publish the version 2.6.1 with corrections. Thank you for pointing that issue.

**Comment by gangstadresta** [comment]
All good ;p
