### ISSUE TITLE
[ERROR_MAXIMUM_TIME_EXCEED] Maximum time is exceed.

### ISSUE THREAD

**Issue by Farhda** [alperensert/capmonster_python#61]
It takes forever then I get this error: [ERROR_MAXIMUM_TIME_EXCEED] Maximum time is exceed.

**Expected behavior**
The script to print the expected report

**Screenshots**
![image](https://github.com/alperensert/capmonster_python/assets/153219681/c4c7a92e-c6e9-42c0-a707-1e3f2c72da3a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version N/A

**Comment by alperensert** [comment]
Hello, @Farhda 

What report do you expected? 
Generally, if the task is not solved within 2 minutes of being created, it will throw a maximum time error.
